name: gravity_sdk
description: "Gravity SDK"
version: 0.10.2
repository: https://github.com/Gravity-Field/gravity-sdk-flutter

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  visibility_detector: ^0.4.0+2
  talker:  ^5.0.2
  talker_dio_logger: ^5.0.2
  collection: ^1.19.1
  uuid: ^4.5.1
  package_info_plus: ^9.0.0
  equatable: 2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.1
  build_version: ^2.1.3


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/


